### ISSUE TITLE
SPARQL_UPDATE=true seems broken

### ISSUE THREAD

**Issue by tkuhn** [tenforce/docker-virtuoso#26] opened 2019-02-21 08:32 UTC
Setting SPARQL_UPDATE=true via docker-compose file works up to tenforce/virtuoso:1.0.0-virtuoso7.2.4, but it seems broken for more recent versions, including tenforce/virtuoso:latest. I found the workaround to run this on the running container:

    $ docker exec -ti $CONTAINERID bash -c 'echo "GRANT SPARQL_UPDATE to \"SPARQL\";" | isql-v -U dba -P dba'

But I didn't manage to find a workaround to bake this fix into an image.

**Comment by nvdk** [comment] 2019-03-06 08:31
Hey @tkuhn,

We've looked into this at [redpencil.io](http://redpencil.io/) and can't reproduce the issue. The following command results in a virtuoso setup that allows sparql update queries on the sparql endpoint. 

```docker run -e SPARQL_UPDATE=true -p 8890:8890 tenforce/virtuoso``` 

Note that in docker-compose.yml you will need to specify true as a string. e.g:
```
    environment:
      SPARQL_UPDATE: "true"
```

**Comment by tkuhn** [comment] 2019-03-06 09:06
You are right, it works with plain docker, but strangely it doesn't via docker-compose. This is the minimal docker-compose.yml file that produces the problem for me:

```
version: '2'
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      - SPARQL_UPDATE:"true"
```

Any ideas what is going wrong here?

**Comment by tkuhn** [comment] 2019-03-06 09:09
Wait, it should have been:

```
version: '2'
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      SPARQL_UPDATE: "true"
```

And now it works! :)

**Comment by nvdk** [comment] 2019-03-06 09:13
Ah yes, this is a common mistake I run into myself sometimes. docker-compose has two ways of specifying env variables:

as a list of strings using equals
```
   environment:
      - "SPARQL_UPDATE=true"
```

or as a dictionary (using colon)

```
   environment:
      SPARQL_UPDATE: "true"
```

The config you provided is a combination of the two and results in a wrong env variable being set, as can be seen using `docker inspect`. It's setting `SPARQL_UPDATE:\"true\"` without a value:

```
"Env": [
                "SPARQL_UPDATE:\"true\"",
                "PATH=/usr/local/virtuoso-opensource/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VIRTUOSO_COMMIT=17c4ba1d5825822d8380ef8d9f978e2d57f4768f"
            ],
```

vs what it should be:
```
 "Env": [
                "SPARQL_UPDATE=true",
                "PATH=/usr/local/virtuoso-opensource/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VIRTUOSO_COMMIT=17c4ba1d5825822d8380ef8d9f978e2d57f4768f"
            ],
```

**Comment by nvdk** [comment] 2019-03-06 09:14
I see you figured that out yourself already :+1:  closing this issue.

**Closed by nvdk** 2019-03-06 09:14 UTC

**Comment by tkuhn** [comment] 2019-03-06 09:27
Yes, that confused me, but I had an earlier version of docker-compose.yml that was fine too. I figured out the problem was a stupid one: I didn't properly clean the mounted volume, which meant some hidden files were kept from earlier runs and that messed up everything.

Thanks for your help!
