### ISSUE TITLE
An error when I want to login

### ISSUE THREAD

**Issue by jtrillos** [tenforce/docker-virtuoso#14] opened 2017-10-02 07:59 UTC
Hi I am new with virtuoso, but I cannot login. I change some things in the docker run
```
docker run --name my-virtuoso \
    -p 8890:8890 -p 1111:1111 \
    -e DBA_PASSWORD=dba \
    -e SPARQL_UPDATE=true \
    -e DEFAULT_GRAPH=http://www.bigdataocean.eu/graph \
    -v /home/jaimetrillos/Documents/BDO/docker-virtuoso/db:/data \
    -d tenforce/virtuoso
```
So, when I go to http://localhost:8890/conductor/ and put user: dba and password: dba. It saids "Invalid credentials". And I do not understand why.

Can you please help me?

**Comment by nvdk** [comment] 2017-10-02 16:21
Hey Jtrillos,

I just tried the exact command you posted and was able to log in with user dba and password dba. Just to verify you have set the correct credentials can you try the following in the shell:

```
echo "status();" | docker exec -i my-virtuoso isql-v 
```

This should return the status of your virtuoso instance.

**Comment by nvdk** [comment] 2017-10-12 13:41
I'm closing this as we can't reproduce the issue and received no further feedback. Feel free to create a new issue if you have a reproducible scenario. Please include as much information as possible such as the docker version used and the result of `docker inspect`.

**Closed by nvdk** 2017-10-12 13:41 UTC
